### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: duckdns-config
    namespace: net-dns
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns-deployment
  namespace: net-dns
  labels:
    app: duckdns
spec:
    replicas: 1
    selector:
        matchLabels:
            app: duckdns
    template:
        metadata:
            labels:
                app: duckdns
        spec:
            volumes:
              - name: mediaserver-volume
                nfs:
                    server: 192.168.1.68
                    path: "/volume1/Data"
            containers:
              - name: duckdns
                image: "lscr.io/linuxserver/duckdns:latest"
                imagePullPolicy: Always
                envFrom:
                - configMapRef:
                    name: duckdns-config
                - secretRef:
                    name: duckdns-secrets
                volumeMounts:
                  - name: mediaserver-volume
                    mountPath: "/config"
                    subPath: Config/DuckDns
                resources:
                  requests: 
                    memory: "50Mi"
                    cpu: "50m"
                  limits:
                    memory: "100Mi"
                    cpu: "100m"          
---