### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: filemigration-config
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    # How many seconds between each action, so as to not overload the old NAS
    TIME_DELAY: "5"
---
### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: filemigration-script
data:
    migrate.sh: |
      echo "Current Time Delay $TIME_DELAY"
      ls -l
      echo "listing files in other"
      ls -l /other_data/ | wc -l
      echo "Listing old media Folder"
      ls -l /old_media/ | wc -l
      echo "Listing old TV media Folder"
      find /old_media/TV -type f | wc -l
      echo "Removing old files from /other/tv"
      find /old_media/TV -type f -exec $SHELL -c '
        echo "$0"
      ' {} \;
      sleep $TIME_DELAY
---
## The Job
apiVersion: batch/v1
kind: Job
metadata:
  name: filemigration-job
spec:
  parallelism: 1    
  completions: 3
  template:
    spec:
      volumes:
      - name: oldnas-volume
        nfs:
          server: 192.168.1.50
          path: "/mnt/MainPool"
      - name: mediaserver-volume
        nfs:
          server: 192.168.1.68
          path: "/volume1/Data"
      - name: filemigration-script
        configMap:
          name: filemigration-script
          defaultMode: 0777
      containers:
      - name: migrate
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args: ["filemigration-script/migrate.sh"]
        envFrom:
        - configMapRef:
            name: filemigration-config
        volumeMounts:
        - mountPath: /filemigration-script
          name: filemigration-script
        - name: mediaserver-volume
          mountPath: "/TV"
          subPath: TV
        - name: oldnas-volume
          mountPath: "/other_data"
          subPath: other
        - name: oldnas-volume
          mountPath: "/old_media"
          subPath: media
      restartPolicy: Never