### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: filemigration-config
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    # How many seconds between each action, so as to not overload the old NAS
    TIME_DELAY: "5"
---
### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: filemigration-script
data:
    migrate.sh: |
      echo "Current Time Delay $TIME_DELAY"
      ls -l
      # Creating function
      removeFiles() {
        echo -ne "\r\e[0K$2 / $3 - $1"
      
      }
      export -f removeFiles
      echo "listing files in other"
      ls -l /other_data/ | wc -l
      echo "Listing old media Folder"
      ls -l /old_media/ | wc -l
      echo "Getting Count of Old TV Downloads"
      let fcount=$(find /other_data/tv -type f | wc -l)
      echo "$fcount"
      echo "Removing old files from /other/tv"
      let i=0
      echo -e "## Starting File removal for /other_data/tv \n \n"
      find /other_data/tv -type f -depth 0 | while read file; do removeFiles "$file" "$i" "$fcount"; ((i++)); sleep $TIME_DELAY; done
      sleep infinity
      find /other_data/tv -type f -exec $SHELL -c '
        echo -n "\r$i / $fcount - "
        echo "$0"
        sleep $TIME_DELAY
        ((i++))
      ' {} \;
      echo "Done!"
      sleep $TIME_DELAY
      sleep infinity
---
## The Job
apiVersion: batch/v1
kind: Job
metadata:
  name: filemigration-job
spec:
  parallelism: 1    
  completions: 3
  template:
    spec:
      volumes:
      - name: oldnas-volume
        nfs:
          server: 192.168.1.50
          path: "/mnt/MainPool"
      - name: mediaserver-volume
        nfs:
          server: 192.168.1.68
          path: "/volume1/Data"
      - name: filemigration-script
        configMap:
          name: filemigration-script
          defaultMode: 0777
      containers:
      - name: migrate
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args: ["filemigration-script/migrate.sh"]
        envFrom:
        - configMapRef:
            name: filemigration-config
        volumeMounts:
        - mountPath: /filemigration-script
          name: filemigration-script
        - name: mediaserver-volume
          mountPath: "/TV"
          subPath: TV
        - name: oldnas-volume
          mountPath: "/other_data"
          subPath: other
        - name: oldnas-volume
          mountPath: "/old_media"
          subPath: media
      restartPolicy: Never