### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: gluetun-config
    namespace: net-dns
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    VPN_SERVICE_PROVIDER: "cyberghost"
    OPENVPN_USER: "abc"
    OPENVPN_PASSWORD: "abc"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  namespace: net-dns
  labels:
    app: gluetun
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gluetun
    template:
        metadata:
            labels:
                app: gluetun
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
          containers:
            - name: gluetun
              envFrom:
              - configMapRef:
                  name: gluetun-config
              image: "lscr.io/qmcgaw/gluetun:latest"
              imagePullPolicy: Always
              readinessProbe:
                  tcpSocket:
                      port: 8888
                  initialDelaySeconds: 20
                  periodSeconds: 15
              ports:  
                - name: vpn-port
                  containerPort: 8888
                  protocol: TCP
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/gluetun"
                  subPath: Config/gluetun
              resources:
                requests: 
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "2048Mi"
                  cpu: "500m"
---
### Service External IP
apiVersion: v1 
kind: Service
metadata:
  name: gluetun-lb-service
  namespace: net-dns
  labels:
    app: gluetun
spec:
  type: LoadBalancer
  ports:
    - port: 9696
      targetPort: vpn-port
  selector:
    app: gluetun
