### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: gluetun-config
    namespace: net-dns
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    VPN_SERVICE_PROVIDER: "privado"
    #SERVER_COUNTRIES: "Canada,France,Netherlands,Singapore,United States"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  namespace: net-dns
  labels:
    app: gluetun
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gluetun
    template:
        metadata:
            labels:
                app: gluetun
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
          containers:
            - name: gluetun
              envFrom:
              - configMapRef:
                  name: gluetun-config
              - secretRef:
                  name: gluetun-secrets
              image: "docker.io/qmcgaw/gluetun:latest"
              imagePullPolicy: Always
              ports:  
                - name: vpn-port
                  containerPort: 8888
                  protocol: TCP
                - name: shadow-tcp
                  containerPort: 8388
                  protocol: TCP
                - name: shadow-udp
                  containerPort: 8388
                  protocol: UDP
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/gluetun"
                  subPath: Config/gluetun
              resources:
                requests: 
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "2048Mi"
                  cpu: "500m"
              securityContext:
                capabilities:
                  add:
                    - NET_ADMIN
