### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: swag-config
    namespace: net-dns
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    URL: "ocnathor.duckdns.org"
    VALIDATION: "dns"
    SUBDOMAINS: "wildcard"
    DNSPLUGIN: "duckdns"
    EMAIL: "aflet54@gmail.com"
    STAGING: "false"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swag-deployment
  namespace: net-dns
  labels:
    app: swag
spec:
    replicas: 1
    selector:
        matchLabels:
            app: swag
    template:
        metadata:
            labels:
                app: swag
        spec:
            volumes:
              - name: mediaserver-volume
                nfs:
                    server: 192.168.1.68
                    path: "/volume1/Data"
            containers:
              - name: swag
                image: "lscr.io/linuxserver/swag:latest"
                imagePullPolicy: Always
                envFrom:
                - configMapRef:
                    name: swag-config
                volumeMounts:
                  - name: mediaserver-volume
                    mountPath: "/config"
                    subPath: Config/SWAG
                ports:  
                  - name: swag-port-http
                    containerPort: 80
                    protocol: TCP
                  - name: swag-port-https
                    containerPort: 443
                    protocol: TCP
                resources:
                  requests: 
                    memory: "50Mi"
                    cpu: "50m"
                  limits:
                    memory: "100Mi"
                    cpu: "100m"          
---
### Service
apiVersion: v1 
kind: Service
metadata:
  name: swag-service
  namespace: net-dns
  labels:
    app: swag
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: swag-port-http
    - port: 443
      name: https
      targetPort: swag-port-https
  selector:
    app: swag