### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: jellyfin-config
    namespace: mediaserver-system
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  namespace: mediaserver-system
  labels:
    app: jellyfin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jellyfin
    template:
        metadata:
            labels:
                app: jellyfin
        spec:
            volumes:
              - name: mediaserver-volume
                nfs:
#                    server: 192.168.1.50
                    server: 192.168.1.68
#                    path: "/mnt/MainPool/media"
                    path: "/volume1/Data"
            containers:
              - name: jellyfin
                image: "lscr.io/linuxserver/jellyfin:latest"
                imagePullPolicy: Always
                envFrom:
                - configMapRef:
                    name: jellyfin-config
                readinessProbe:
                    tcpSocket:
                        port: 8096
                    initialDelaySeconds: 20
                    periodSeconds: 15
                ports:  
                  - name: jellyfin-port
                    containerPort: 8096
                    protocol: TCP
                volumeMounts:
                  - name: mediaserver-volume
                    mountPath: "/config"
                    subPath: Config/Jellyfin
                  - name: mediaserver-volume
                    mountPath: "/cert-config"
                    subPath: Config/SWAG
                  - name: mediaserver-volume
                    mountPath: "/Movies"
                    subPath: Movies
                  - name: mediaserver-volume
                    mountPath: "/TV"
                    subPath: TV
                resources:
                  requests: 
                    memory: "256Mi"
                    cpu: "250m"
                  limits:
                    memory: "2048Mi"
                    cpu: "500m"
                    
---
### Service
apiVersion: v1 
kind: Service
metadata:
  name: jellyfin-service
  namespace: mediaserver-system
  labels:
    app: jellyfin
spec:
  type: LoadBalancer
  ports:
    - port: 8096
      targetPort: jellyfin-port 
  selector:
    app: jellyfin