### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: plex-config
data:
    PGID: "1000"
    PUID: "1000"
    PLEX_CLAIM: "claim-yBw6yY81H6fdDKCQTSrs"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: mediaserver-system
  labels:
    app: plex
spec:
    replicas: 1
    selector:
        matchLabels:
            app: plex
    template:
        metadata:
            labels:
                app: plex
        spec:
            volumes:
              - name: mediaserver-volume
                nfs:
                    server: 192.168.1.50
                    path: "/mnt/MainPool/media"
            containers:
              - name: plex
                image: "docker.io/linuxserver/plex:latest"
                imagePullPolicy: Always
                readinessProbe:
                    tcpSocket:
                        port: 32400
                    initialDelaySeconds: 20
                    periodSeconds: 15
                ports:  
                  - name: plex-port
                    containerPort: 32400
                    protocol: TCP
                volumeMounts:
                  - name: mediaserver-volume
                    mountPath: "/config"
                    subPath: config/plex
                  - name: mediaserver-volume
                    mountPath: "/Movies"
                    subPath: Movies
                  - name: mediaserver-volume
                    mountPath: "/TV"
                    subPath: TV
                resources:
                    
---
### Service
apiVersion: v1 
kind: Service
metadata:
  name: plex-service
  namespace: mediaserver-system
  labels:
    app: plex
spec:
  ports:
    - port: 32400
      targetPort: plex-port
  selector:
    app: plex
---
### Ingress / External Access Path
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: mediaserver-system
spec:
  rules:
  - host: plex.ocnathor.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex-service
            port:
              number: 8080