### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: plex-config
data:
    PGID: "1000"
    PUID: "1000"
    PLEX_CLAIM: ""
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  namespace: mediaserver-system
  labels:
    app: plex
spec:
    replicas: 1
    selector:
        matchLabels:
            app: plex
    template:
        metadata:
            labels:
                app: plex
        spec:
            volumes:
              - name: mediaserver-volume
                nfs:
                    server: 192.168.1.50
                    path: "/media"
            containers:
              - name: plex
                image: "docker.io/linuxserver/plex:latest"
                imagePullPolicy: Always
                readinessProbe:
                    tcpSocket:
                        port: 32400
                    initialDelaySeconds: 20
                    periodSeconds: 15
                ports:  
                  - name: plex-port
                    containerPort: 32400
                    protocol: TCP
                volumeMounts:
                  - name: mediaserver-volume
                    mountPath: "/config"
                    subPath: config/plex
                  - name: mediaserver-volume
                    mountPath: "/moives"
                    subPath: moives
                  - name: mediaserver-volume
                    mountPath: "/tv"
                    subPath: tv
                resources:
                    
---
### Service
apiVersion: v1 
kind: Service
metadata:
  name: plex-service
spec:
  type: NodePort
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: plex-port
      # nodePort: 30007
  selector:
    app: plex