### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: jackett-config
    namespace: downloaders
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett-deployment
  namespace: downloaders
  labels:
    app: jackett
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jackett
    template:
        metadata:
            labels:
                app: jackett
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
          containers:
            - name: jackett
              envFrom:
              - configMapRef:
                  name: jackett-config
              image: "lscr.io/linuxserver/jackett:latest"
              imagePullPolicy: Always
              readinessProbe:
                  tcpSocket:
                      port: 9117
                  initialDelaySeconds: 20
                  periodSeconds: 15
              ports:  
                - name: trans-port
                  containerPort: 9117
                  protocol: TCP
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/config"
                  subPath: Config/jackett
                - name: mediaserver-volume
                  mountPath: "/downloads"
                  subPath: Downloads/
              resources:
                requests: 
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "2048Mi"
                  cpu: "500m"
---
### Service External IP
apiVersion: v1 
kind: Service
metadata:
  name: jackett-lb-service
  namespace: downloaders
  labels:
    app: jackett
spec:
  type: LoadBalancer
  ports:
    - port: 9117
      targetPort: trans-port
  selector:
    app: jackett
