### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: transmission-config
    namespace: downloaders
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    TRANSMISSION_WEB_HOME: "/combustion-release/"
    PEERPORT: "51413"
    USER: "TRANS"
    PASS: "TPASS"
---
### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: gluetun-config
    namespace: downloaders
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    VPN_SERVICE_PROVIDER: "privado"
    #SERVER_COUNTRIES: "Canada,France,Netherlands,Singapore,United States"
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
  namespace: downloaders
  labels:
    app: transmission
spec:
    replicas: 1
    selector:
        matchLabels:
            app: transmission
    template:
        metadata:
            labels:
                app: transmission
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
          containers:
            - name: transmission
              envFrom:
              - configMapRef:
                  name: transmission-config
              image: "lscr.io/linuxserver/transmission:latest"
              imagePullPolicy: Always
              readinessProbe:
                  tcpSocket:
                      port: 9091
                  initialDelaySeconds: 20
                  periodSeconds: 15
              ports:  
                - name: trans-port
                  containerPort: 9091
                  protocol: TCP
                - name: trans-peer-tcp
                  containerPort: 51413
                  protocol: TCP
                - name: trans-peer-udp
                  containerPort: 51413
                  protocol: UDP
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/config"
                  subPath: Config/transmission
                - name: mediaserver-volume
                  mountPath: "/Downloads"
                  subPath: Downloads
              resources:
                requests: 
                  memory: "256Mi"
                  cpu: "250m"
                limits:
                  memory: "2048Mi"
                  cpu: "500m"
            - name: gluetun
              envFrom:
              - configMapRef:
                  name: gluetun-config
              - secretRef:
                  name: gluetun-secret
              image: "docker.io/qmcgaw/gluetun:latest"
              imagePullPolicy: Always
              ports:  
                - name: vpn-port
                  containerPort: 8888
                  protocol: TCP
                - name: shadow-tcp
                  containerPort: 8388
                  protocol: TCP
                - name: shadow-udp
                  containerPort: 8388
                  protocol: UDP
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/gluetun"
                  subPath: Config/gluetun
              resources: {}
              securityContext:
                capabilities:
                  add:
                    - NET_ADMIN
---
### Service External IP
apiVersion: v1 
kind: Service
metadata:
  name: transmission-lb-service
  namespace: downloaders
  labels:
    app: transmission
spec:
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: trans-port
  selector:
    app: transmission
apiVersion: v1
---
### Service External IP - peer TCP
apiVersion: v1 
kind: Service
metadata:
  name: trans-peer-tcp
  namespace: downloaders
  labels:
    app: transmission
spec:
  type: ClusterIP
  ports:
    - port: 51413
      targetPort: trans-peer-tcp
      protocol: TCP
  selector:
    app: transmission
apiVersion: v1
---
### Service External IP - peer UDP
apiVersion: v1 
kind: Service
metadata:
  name: trans-peer-udp
  namespace: downloaders
  labels:
    app: transmission
spec:
  type: ClusterIP
  ports:
    - port: 51413
      targetPort: trans-peer-udp
      protocol: UDP
  selector:
    app: transmission
apiVersion: v1
