### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: azure-agent-config
    namespace: azure
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    ORGURL: "https://dev.azure.com/ocnathor"
---
### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: azure-agent-startupscript
    namespace: azure
data:
    startup.sh: |
      echo "Starting Azure Client Agent"
      cd ~
      apt-get update
      apt-get install wget -y
      wget -O vsts-agent-linux-latest.tar.gz https://vstsagentpackage.azureedge.net/agent/2.213.2/vsts-agent-linux-x64-2.213.2.tar.gz
      mkdir myagent && cd myagent
      tar zxvf ../vsts-agent-linux-latest.tar.gz
      ./run.sh --unattended
      sleep infinity
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-agent-deployment
  namespace: azure
  labels:
    app: azure-agent
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-agent
    template:
        metadata:
            labels:
                app: azure-agent
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
            - name: azure-agent-startupscript
              configMap:
                name: azure-agent-startupscript
                defaultMode: 0777
          containers:
            - name: azure-agent
              image: ubuntu
              command: ["/bin/bash", "-c"]
              args: ["/azure-agent-startupscript/startup.sh"]
              envFrom:
              - configMapRef:
                  name: azure-agent-config
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/config"
                  subPath: Config/azure-agent
                - name: azure-agent-startupscript
                  mountPath: /azure-agent-startupscript
                  
              resources:
                requests: 
                  memory: "256Mi"
                limits:
                  memory: "2048Mi"