### Application Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: azure-agent-config
    namespace: azure
data:
    PGID: "1000"
    PUID: "1000"
    TZ: "Australia/Brisbane"
    ORGURL: "https://dev.azure.com/ocnathor"
---
### Config Map
apiVersion: v1
kind: ConfigMap
metadata:
    name: azure-agent-startupscript
    namespace: azure
data:
    startup.sh: |
      echo "Starting Azure Client Agent"
      cd /tmp
      groupadd -g $PGID abcGroup
      useradd abcUser -u $PUID -g $PGID -m -s /bin/bash
      apt-get update
      apt-get install -y icu-devtools wget libcurl4 libssl-dev
      wget -O /tmp/vsts-agent-linux-latest.tar.gz https://vstsagentpackage.azureedge.net/agent/2.213.2/vsts-agent-linux-x64-2.213.2.tar.gz
      mkdir /tmp/myagent && cd /tmp/myagent
      mkdir /tmp/workingDir
      tar zxvf ../vsts-agent-linux-latest.tar.gz
      chown abcUser /tmp --recursive
      chgrp abcGroup /tmp --recursive
      su abcUser
      ./config.sh --unattended --url $ORGURL --auth pat --token $PAT_TOKEN --pool default --agent myAgent --acceptTeeEula
      sleep infinity
---
### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-agent-deployment
  namespace: azure
  labels:
    app: azure-agent
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azure-agent
    template:
        metadata:
            labels:
                app: azure-agent
        spec:
          volumes:
            - name: mediaserver-volume
              nfs:
                server: 192.168.1.68
                path: "/volume1/Data"
            - name: azure-agent-startupscript
              configMap:
                name: azure-agent-startupscript
                defaultMode: 0777
          containers:
            - name: azure-agent
              image: ubuntu
              command: ["/bin/bash", "-c"]
              args: ["/azure-agent-startupscript/startup.sh"]
              envFrom:
              - configMapRef:
                  name: azure-agent-config
              - secretRef:
                  name: azure-secret
              volumeMounts:
                - name: mediaserver-volume
                  mountPath: "/config"
                  subPath: Config/azure-agent
                - name: azure-agent-startupscript
                  mountPath: /azure-agent-startupscript
              resources:
                requests: 
                  memory: "256Mi"
                limits:
                  memory: "2048Mi"