apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: azure
type: Opaque
data:
  # https://www.duckdns.org/domains token
  # Don't forget to update from the website
  AZP_TOKEN: bWVnYV9zZWNyZXRfa2V5Cg==